name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Install curl and pkg-config
        run: sudo apt install -y curl pkg-config
      - name: Install libvips
        run: curl -s https://raw.githubusercontent.com/h2non/bimg/master/preinstall.sh | sudo bash -
      - name: Install dependencies
        run: go get -t -v ./...
      - name: Build
        run: ./build.sh
      - name: Run tests
        run: go test -v ./...
      - name: Run static analysis
        run: ./run_lints.sh
      - name: Run coverage
        run: go test -coverprofile=coverage.out -v ./...
        env:
          GO111MODULE: "on"
