name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Install libvips
        run: sudo apt-get update && sudo apt-get install -y libvips-dev
      - name: Install dependencies
        run: go get -t -v ./...
      - name: Build
        run: ./build.sh
      - name: Run tests
        run: go test -v ./...
      - name: Run static analysis
        run: ./run_lints.sh
      - name: Run coverage
        run: go test -coverprofile=coverage.out -v ./...
        env:
          GO111MODULE: "on"
